<?php

// Enter your twitter ID:
$twitterid = "robportman";

// Enter your Google Analytics info
define('ga_email','emotivemaster@gmail.com');
define('ga_password','carlyle99');
define('ga_profile_id','14845720');

// Enter your database info
$mysql_host = "mysql50-76.wc1.dfw1.stabletransit.com";
$mysql_db = "375570_civicrm";
$mysql_login = "375570_matt";
$mysql_pass = "Emotive1";

// Enter your Facebook Info
$facebook_page = "185550966885";


// Enter search term
$search_keywords = '"Rob+Portman"';


// Enter campaign information
$max_donation = 4800;
$primary_date = "2009-04-01";  // Format: YYYY-MM-DD

//Quantcast Settings
$quantcast_domain = "org.mlkmemorial";
$quantcast_id = "aaUdmKa8sDZoM";

?>